name: Diagnostic Build

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Diagnostic Check
      run: |
        echo "=== Files in repo ==="
        ls -la
        
        echo -e "\n=== Swift files ==="
        find . -name "*.swift" -type f | head -10
        
        echo -e "\n=== Check if xcodeproj exists ==="
        ls -la *.xcodeproj || echo "No xcodeproj found"
        
        echo -e "\n=== Try simple Swift build ==="
        # Create a minimal single-file iOS app
        cat > MinimalApp.swift << 'EOF'
        import UIKit

        @main
        class AppDelegate: UIResponder, UIApplicationDelegate {
            var window: UIWindow?
            
            func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                window = UIWindow(frame: UIScreen.main.bounds)
                let vc = UIViewController()
                vc.view.backgroundColor = .systemBlue
                window?.rootViewController = vc
                window?.makeKeyAndVisible()
                return true
            }
        }
        EOF
        
        echo -e "\n=== Create minimal Info.plist if missing ==="
        if [ ! -f Info.plist ]; then
          cat > Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleDevelopmentRegion</key>
          <string>en</string>
          <key>CFBundleExecutable</key>
          <string>$(EXECUTABLE_NAME)</string>
          <key>CFBundleIdentifier</key>
          <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
          <key>CFBundleInfoDictionaryVersion</key>
          <string>6.0</string>
          <key>CFBundleName</key>
          <string>$(PRODUCT_NAME)</string>
          <key>CFBundlePackageType</key>
          <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
          <key>CFBundleShortVersionString</key>
          <string>1.0</string>
          <key>CFBundleVersion</key>
          <string>1</string>
          <key>UILaunchStoryboardName</key>
          <string>LaunchScreen</string>
          <key>UIRequiredDeviceCapabilities</key>
          <array>
            <string>armv7</string>
          </array>
          <key>UISupportedInterfaceOrientations</key>
          <array>
            <string>UIInterfaceOrientationPortrait</string>
          </array>
        </dict>
        </plist>
        EOF
        fi
        
        echo -e "\n=== Try xcrun build ==="
        xcrun -sdk iphoneos swiftc \
          -target arm64-apple-ios16.0 \
          -o FlirtFrame \
          MinimalApp.swift || echo "Direct build failed"
          
        echo -e "\n=== Check what was built ==="
        ls -la FlirtFrame* || echo "No output found"