name: Direct Firebase Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Create Xcode Project
      run: |
        echo "📱 Creating Xcode project directly..."
        
        # Create xcodeproj structure
        mkdir -p FlirtFrame.xcodeproj/project.xcworkspace/xcshareddata
        mkdir -p FlirtFrame.xcodeproj/xcshareddata/xcschemes
        
        # Create workspace settings
        cat > FlirtFrame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>IDEDidComputeMac32BitWarning</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Create workspace data
        cat > FlirtFrame.xcodeproj/project.xcworkspace/contents.xcworkspacedata << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <Workspace
           version = "1.0">
           <FileRef
              location = "self:">
           </FileRef>
        </Workspace>
        EOF
        
    - name: Generate Project with SPM
      run: |
        echo "🔨 Generating project with Swift Package Manager..."
        
        # Generate xcodeproj from Package.swift
        swift package generate-xcodeproj
        
        # Update settings for no code signing
        /usr/libexec/PlistBuddy -c "Set :objects:*:buildSettings:CODE_SIGN_IDENTITY ''" FlirtFrame.xcodeproj/project.pbxproj || true
        /usr/libexec/PlistBuddy -c "Set :objects:*:buildSettings:CODE_SIGNING_REQUIRED 'NO'" FlirtFrame.xcodeproj/project.pbxproj || true
        /usr/libexec/PlistBuddy -c "Set :objects:*:buildSettings:CODE_SIGNING_ALLOWED 'NO'" FlirtFrame.xcodeproj/project.pbxproj || true
        
    - name: Resolve Dependencies
      run: |
        echo "📦 Resolving Firebase dependencies..."
        
        # Resolve packages
        xcodebuild -resolvePackageDependencies \
          -project FlirtFrame.xcodeproj \
          -scheme FlirtFrame-Package
          
        # Give time for downloads
        sleep 30
        
    - name: Build App
      run: |
        echo "🔨 Building FlirtFrame..."
        
        # List available schemes
        xcodebuild -list -project FlirtFrame.xcodeproj
        
        # Build for device
        xcodebuild build \
          -project FlirtFrame.xcodeproj \
          -scheme FlirtFrame-Package \
          -configuration Release \
          -sdk iphoneos \
          -destination "generic/platform=iOS" \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM="" \
          -allowProvisioningUpdates || {
            echo "❌ Build failed"
            find DerivedData -name "*.xcactivitylog" -exec echo "=== {} ===" \; -exec tail -100 {} \;
            exit 1
          }
          
    - name: Create IPA  
      run: |
        echo "📦 Creating IPA package..."
        
        # Find the app
        APP_PATH=$(find DerivedData -name "*.app" -type d | grep -E "Release-iphoneos" | head -1)
        
        if [ -z "$APP_PATH" ]; then
          echo "❌ No app bundle found!"
          find DerivedData -name "*.app" -type d
          exit 1
        fi
        
        echo "✅ Found app at: $APP_PATH"
        
        # Create Payload
        mkdir -p Payload
        cp -R "$APP_PATH" Payload/
        
        # Create IPA
        zip -qr FlirtFrame-Direct.ipa Payload
        
        echo "✅ IPA created successfully!"
        ls -lh FlirtFrame-Direct.ipa
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FlirtFrame-Direct-Firebase
        path: FlirtFrame-Direct.ipa
        if-no-files-found: error
        retention-days: 7