name: Iterative Build v2 Fixed - Photo Picker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Step 2 - Add Photo Picker (Fixed)
      run: |
        echo "🎯 Step 2: Adding photo picker - avoiding duplicate @main..."
        
        # Clean workspace completely
        rm -rf FlirtFrame.xcodeproj DerivedData Payload *.ipa
        rm -rf BuildSource  # Use unique directory name
        
        # Create isolated source directory
        mkdir -p BuildSource
        
        # Add photo picker functionality - only ONE @main
        cat > BuildSource/FlirtFrameApp.swift << 'EOF'
        import SwiftUI
        import PhotosUI
        
        @main
        struct FlirtFrameApp: App {
            var body: some Scene {
                WindowGroup {
                    ContentView()
                }
            }
        }
        
        struct ContentView: View {
            @State private var selectedItem: PhotosPickerItem?
            @State private var selectedImage: UIImage?
            
            var body: some View {
                VStack(spacing: 20) {
                    Text("FlirtFrame")
                        .font(.largeTitle)
                        .bold()
                    
                    if let image = selectedImage {
                        Image(uiImage: image)
                            .resizable()
                            .scaledToFit()
                            .frame(maxHeight: 300)
                            .cornerRadius(10)
                    } else {
                        RoundedRectangle(cornerRadius: 10)
                            .fill(Color.gray.opacity(0.2))
                            .frame(height: 300)
                            .overlay(
                                Text("No photo selected")
                                    .foregroundColor(.gray)
                            )
                    }
                    
                    PhotosPicker(
                        selection: $selectedItem,
                        matching: .images,
                        photoLibrary: .shared()
                    ) {
                        Label("Select Photo", systemImage: "photo")
                            .font(.title3)
                            .padding()
                            .background(Color.blue)
                            .foregroundColor(.white)
                            .cornerRadius(10)
                    }
                    .onChange(of: selectedItem) { newItem in
                        Task {
                            if let data = try? await newItem?.loadTransferable(type: Data.self),
                               let image = UIImage(data: data) {
                                selectedImage = image
                            }
                        }
                    }
                    
                    if selectedImage != nil {
                        Button("Generate Openers") {
                            print("Generate openers for image")
                        }
                        .buttonStyle(.borderedProminent)
                        .controlSize(.large)
                    }
                    
                    Spacer()
                }
                .padding()
            }
        }
        EOF
        
        # Update Info.plist with photo permissions
        cat > Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>FlirtFrame</string>
            <key>CFBundleIdentifier</key>
            <string>com.flirtframe.app</string>
            <key>CFBundleName</key>
            <string>FlirtFrame</string>
            <key>CFBundleDisplayName</key>
            <string>FlirtFrame</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>2</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UISupportedInterfaceOrientations</key>
            <array>
                <string>UIInterfaceOrientationPortrait</string>
            </array>
            <key>NSPhotoLibraryUsageDescription</key>
            <string>FlirtFrame needs access to your photos to generate conversation starters</string>
        </dict>
        </plist>
        EOF
        
        # Create project.yml that ONLY includes our BuildSource
        cat > project.yml << 'EOF'
        name: FlirtFrame
        options:
          bundleIdPrefix: com.flirtframe
          createIntermediateGroups: true
          deploymentTarget:
            iOS: 16.0
        settings:
          base:
            PRODUCT_NAME: FlirtFrame
            PRODUCT_BUNDLE_IDENTIFIER: com.flirtframe.app
            MARKETING_VERSION: 1.0
            CURRENT_PROJECT_VERSION: 2
            DEVELOPMENT_TEAM: ""
            CODE_SIGN_STYLE: Manual
            CODE_SIGN_IDENTITY: ""
            CODE_SIGNING_REQUIRED: "NO"
            CODE_SIGNING_ALLOWED: "NO"
            PROVISIONING_PROFILE_SPECIFIER: ""
            INFOPLIST_FILE: Info.plist
            IPHONEOS_DEPLOYMENT_TARGET: 16.0
            SWIFT_VERSION: 5.0
            TARGETED_DEVICE_FAMILY: 1,2
        targets:
          FlirtFrame:
            type: application
            platform: iOS
            deploymentTarget: 16.0
            sources:
              - path: BuildSource
                excludes:
                  - "**/*.md"
            settings:
              base:
                INFOPLIST_FILE: Info.plist
                PRODUCT_BUNDLE_IDENTIFIER: com.flirtframe.app
        EOF
        
        echo "✅ Created isolated build with photo picker"
        
    - name: Generate and Build
      run: |
        brew install xcodegen || brew upgrade xcodegen || true
        xcodegen generate --spec project.yml
        
        echo "Building app..."
        xcodebuild build \
          -project FlirtFrame.xcodeproj \
          -scheme FlirtFrame \
          -configuration Release \
          -sdk iphoneos \
          -destination "generic/platform=iOS" \
          -derivedDataPath "$PWD/DerivedData" \
          ONLY_ACTIVE_ARCH=NO \
          ARCHS="arm64" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO || {
            echo "Build failed, checking for @main conflicts..."
            find . -name "*.swift" -exec grep -l "@main" {} \;
            exit 1
          }
          
    - name: Create IPA
      run: |
        APP_PATH=$(find DerivedData -name "*.app" -type d | grep -E "Release-iphoneos" | head -1)
        
        if [ -z "$APP_PATH" ]; then
          echo "ERROR: No app found!"
          exit 1
        fi
        
        echo "Found app at: $APP_PATH"
        
        mkdir -p Payload
        cp -R "$APP_PATH" Payload/
        zip -qr FlirtFrame-v2-fixed.ipa Payload
        
        echo "✅ Photo picker app built successfully!"
        ls -lh FlirtFrame-v2-fixed.ipa
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FlirtFrame-v2-PhotoPicker-Fixed
        path: FlirtFrame-v2-fixed.ipa
        if-no-files-found: error