name: Iterative Build v4 - Integrate Real Source

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Step 4 - Integrate Real FlirtFrame Source
      run: |
        echo "🎯 Step 4: Integrating real FlirtFrame source files..."
        
        # Clean workspace
        rm -rf FlirtFrame.xcodeproj DerivedData Payload *.ipa
        rm -rf BuildSourceV4
        
        # Create build directory
        mkdir -p BuildSourceV4
        
        # Copy select source files (avoiding duplicate @main)
        echo "Copying essential source files..."
        
        # First, check which files have @main
        echo "Files with @main attribute:"
        find Sources -name "*.swift" -exec grep -l "@main" {} \; || echo "No @main found"
        
        # Copy FlirtFrameApp.swift but ensure it's the only @main
        if [ -f "Sources/FlirtFrameApp.swift" ]; then
          cp Sources/FlirtFrameApp.swift BuildSourceV4/
        else
          # Create a minimal app entry if missing
          cat > BuildSourceV4/FlirtFrameApp.swift << 'EOF'
        import SwiftUI
        
        @main
        struct FlirtFrameApp: App {
            var body: some Scene {
                WindowGroup {
                    ContentView()
                }
            }
        }
        EOF
        fi
        
        # Copy other source files WITHOUT @main
        for file in Sources/*.swift; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            # Skip files that might have @main or conflict
            if [[ "$filename" != "FlirtFrameApp.swift" && "$filename" != "SimpleApp.swift" && "$filename" != "App.swift" ]]; then
              echo "Copying $filename..."
              # Remove any @main attributes just in case
              sed 's/@main//g' "$file" > "BuildSourceV4/$filename"
            fi
          fi
        done
        
        # If ContentView doesn't exist, create a simple one
        if [ ! -f "BuildSourceV4/ContentView.swift" ]; then
          cat > BuildSourceV4/ContentView.swift << 'EOF'
        import SwiftUI
        
        struct ContentView: View {
            var body: some View {
                NavigationView {
                    VStack(spacing: 20) {
                        Text("FlirtFrame")
                            .font(.largeTitle)
                            .bold()
                        
                        Text("AI-Powered Dating Openers")
                            .font(.title2)
                            .foregroundColor(.secondary)
                        
                        Spacer()
                        
                        Button(action: {
                            print("Start camera flow")
                        }) {
                            Label("Take Photo", systemImage: "camera.fill")
                                .font(.title3)
                                .padding()
                                .frame(maxWidth: .infinity)
                                .background(Color.blue)
                                .foregroundColor(.white)
                                .cornerRadius(10)
                        }
                        
                        Button(action: {
                            print("Select from gallery")
                        }) {
                            Label("Choose from Gallery", systemImage: "photo.fill")
                                .font(.title3)
                                .padding()
                                .frame(maxWidth: .infinity)
                                .background(Color.green)
                                .foregroundColor(.white)
                                .cornerRadius(10)
                        }
                        
                        Spacer()
                    }
                    .padding()
                    .navigationBarTitleDisplayMode(.inline)
                }
            }
        }
        EOF
        fi
        
        # Create stubs for Firebase if needed
        if grep -r "FirebaseManager\|FirebaseApp" BuildSourceV4/*.swift > /dev/null 2>&1; then
          echo "Creating Firebase stubs..."
          cat > BuildSourceV4/FirebaseStubs.swift << 'EOF'
        import Foundation
        
        // Firebase stubs to allow compilation without Firebase SDK
        class FirebaseApp {
            static func configure() {
                print("[Stub] Firebase configured")
            }
        }
        
        class FirebaseManager {
            static let shared = FirebaseManager()
            
            func configure() {
                print("[Stub] FirebaseManager configured")
            }
        }
        
        @objc class FIRApp: NSObject {
            @objc static func configure() {
                print("[Stub] FIRApp configured")
            }
        }
        EOF
        fi
        
        # Create AppState if missing
        if [ ! -f "BuildSourceV4/AppState.swift" ]; then
          cat > BuildSourceV4/AppState.swift << 'EOF'
        import SwiftUI
        
        class AppState: ObservableObject {
            @Published var hasCompletedOnboarding = true
            @Published var isLoading = false
        }
        EOF
        fi
        
        # Update Info.plist
        if [ -f "Info.plist" ]; then
          cp Info.plist Info.plist.build
        else
          cat > Info.plist.build << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>FlirtFrame</string>
            <key>CFBundleIdentifier</key>
            <string>com.flirtframe.app</string>
            <key>CFBundleName</key>
            <string>FlirtFrame</string>
            <key>CFBundleDisplayName</key>
            <string>FlirtFrame</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>4</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UISupportedInterfaceOrientations</key>
            <array>
                <string>UIInterfaceOrientationPortrait</string>
            </array>
            <key>NSPhotoLibraryUsageDescription</key>
            <string>FlirtFrame needs access to your photos to generate conversation starters</string>
            <key>NSCameraUsageDescription</key>
            <string>FlirtFrame needs camera access to take photos for analysis</string>
        </dict>
        </plist>
        EOF
        fi
        
        # Project configuration
        cat > project.yml << 'EOF'
        name: FlirtFrame
        options:
          bundleIdPrefix: com.flirtframe
          createIntermediateGroups: true
          deploymentTarget:
            iOS: 16.0
        settings:
          base:
            PRODUCT_NAME: FlirtFrame
            PRODUCT_BUNDLE_IDENTIFIER: com.flirtframe.app
            MARKETING_VERSION: 1.0
            CURRENT_PROJECT_VERSION: 4
            DEVELOPMENT_TEAM: ""
            CODE_SIGN_STYLE: Manual
            CODE_SIGN_IDENTITY: ""
            CODE_SIGNING_REQUIRED: "NO"
            CODE_SIGNING_ALLOWED: "NO"
            PROVISIONING_PROFILE_SPECIFIER: ""
            INFOPLIST_FILE: Info.plist.build
            IPHONEOS_DEPLOYMENT_TARGET: 16.0
            SWIFT_VERSION: 5.0
            TARGETED_DEVICE_FAMILY: 1,2
        targets:
          FlirtFrame:
            type: application
            platform: iOS
            deploymentTarget: 16.0
            sources:
              - path: BuildSourceV4
                excludes:
                  - "**/*.md"
            resources:
              - path: Assets.xcassets
                optional: true
            settings:
              base:
                INFOPLIST_FILE: Info.plist.build
                PRODUCT_BUNDLE_IDENTIFIER: com.flirtframe.app
        EOF
        
        echo "✅ Integrated real source files"
        echo "Files in build directory:"
        ls -la BuildSourceV4/
        
    - name: Generate and Build
      run: |
        brew install xcodegen || brew upgrade xcodegen || true
        xcodegen generate --spec project.yml
        
        # Remove Firebase imports before building
        find BuildSourceV4 -name "*.swift" -exec sed -i '' 's/import Firebase/\/\/import Firebase/g' {} \;
        find BuildSourceV4 -name "*.swift" -exec sed -i '' 's/import FirebaseAuth/\/\/import FirebaseAuth/g' {} \;
        find BuildSourceV4 -name "*.swift" -exec sed -i '' 's/import FirebaseFirestore/\/\/import FirebaseFirestore/g' {} \;
        
        xcodebuild build \
          -project FlirtFrame.xcodeproj \
          -scheme FlirtFrame \
          -configuration Release \
          -sdk iphoneos \
          -destination "generic/platform=iOS" \
          -derivedDataPath "$PWD/DerivedData" \
          ONLY_ACTIVE_ARCH=NO \
          ARCHS="arm64" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO || {
            echo "Build failed. Checking errors..."
            # Show which files were included
            echo "=== Build directory contents ==="
            ls -la BuildSourceV4/
            echo "=== Checking for syntax errors ==="
            find BuildSourceV4 -name "*.swift" -exec swiftc -parse {} \; 2>&1 | head -20
            exit 1
          }
          
    - name: Create IPA
      run: |
        APP_PATH=$(find DerivedData -name "*.app" -type d | grep -E "Release-iphoneos" | head -1)
        mkdir -p Payload
        cp -R "$APP_PATH" Payload/
        zip -qr FlirtFrame-v4.ipa Payload
        
        echo "✅ Real FlirtFrame app built successfully!"
        ls -lh FlirtFrame-v4.ipa
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FlirtFrame-v4-Real-Source
        path: FlirtFrame-v4.ipa
        if-no-files-found: error